### ISSUE TITLE
Passing the wasm module into a web-worker

### ISSUE THREAD

**Issue by inzanez** [paulocoutinhox/pdfium-lib#100]
Hi

did anyone succeed passing that WASM module into a web worker? I tried different techniques so far, but up until now always failed.

**Comment by Priestch** [comment]
@inzanez If you only want to use the wasm in a web worker, you should create and use the module in the web worker. 

Passing data from the main thread to a worker thread has restrictions due to transferable objects and the structured clone algorithm. You can read more about [transferable objects](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects) and [structured clone](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) to figure out why it not gona work.

**Comment by inzanez** [comment]
@Priestch I see. Yeah, I just never managed to create the wasm module in the worker because the standard 'js' file is not a module, and therefore I would need to use `importScripts` which does not exist in a module worker.
So I had to manually patch the emscripten generated 'js' file.

**Comment by Priestch** [comment]
@inzanez You can try to use some bundler tool to bundle the wasm js file to the worker js file, then you hopefully can use the worker like before.

**Comment by inzanez** [comment]
@Priestch Yes, that seems to work out! Thanks
