### ISSUE TITLE
Latest release is missing WASM-build

### ISSUE THREAD

**Issue by swftvsn** [paulocoutinhox/pdfium-lib#101]
Was there a problem with the build?

**Comment by paulocoutinhox** [comment]
Yes, i need find a new way to don't download too much things when clone repository, because don't left space on disk.

**Comment by hyzyla** [comment]
As idea, you can build project with [checkout_configuration=minimal](https://pdfium.googlesource.com/pdfium/+/refs/heads/main/DEPS#15) options, but it definetly tradeoff:

>  By default, we should check out everything needed to run on the main
pdfium waterfalls. This var can be also be set to 'small', in order to skip
things are not strictly needed to build pdfium for development purposes,
by adding the following line to the .gclient file inside a solutions entry:
     "custom_vars": { "checkout_configuration": "small" },
Similarly, this var can be set to 'minimal' to also skip the Skia and V8
checkouts for the smallest possible checkout, where some features will not
work.

**Comment by paulocoutinhox** [comment]
Hi,

I have updated everything.

You can now use the latest version.

Thanks.

**Comment by swftvsn** [comment]
Awesome, thank you for your work!
