### ISSUE TITLE
Support for cross platform frameworks

### ISSUE THREAD

**Issue by DImuthuUpe** [paulocoutinhox/pdfium-lib#107]
Does pdfium-lib work with frameworks like React Native or Flutter? We plan to rewrite our mobile app in either of those frameworks and it has a pdf rendering component. Also, if it requires work, we can contribute to the repository.

**Comment by paulocoutinhox** [comment]
Hi,

Yes, it works with any framework, since these frameworks use native iOS/Android libraries too. You need call C++ functions from React/Flutter.

I have projects that do exactly this:
- https://github.com/xplpc/xplpc
- https://github.com/nativium/nativium

A pseudo-code:

C++ Function:

```cpp
#include <vector>
#include <string>

extern "C" {
    std::vector<uint8_t> processImage(const std::string &input) {
        // Sua lógica de processamento de imagem aqui
        std::vector<uint8_t> imageBytes; 
        return imageBytes;
    }
}
```

React:

```js
import { NativeModules } from 'react-native';
const { MyImageProcessor } = NativeModules;

const getImageBytes = async (inputString) => {
  const bytes = await MyImageProcessor.processImage(inputString);
  return bytes;
};
```

Flutter:

```dart
// ffi part
import 'dart:ffi';
import 'package:ffi/ffi.dart';

typedef process_image_func = Pointer<Uint8> Function(Pointer<Utf8>);
typedef ProcessImage = Pointer<Uint8> Function(Pointer<Utf8>);

final dylib = DynamicLibrary.open('path_to_your_library');
final ProcessImage processImage = dylib
    .lookup<NativeFunction<process_image_func>>('processImage')
    .asFunction();
```

```dart
// call function
Pointer<Utf8> inputString = 'your_input_string'.toNativeUtf8();
Pointer<Uint8> imageBytes = processImage(inputString);
```

Each framework has tutorials about it:

- React: https://reactnative.dev/docs/next/the-new-architecture/cxx-cxxturbomodules
- Flutter: https://docs.flutter.dev/platform-integration/android/c-interop and https://docs.flutter.dev/platform-integration/ios/c-interop

**Comment by DImuthuUpe** [comment]
Thanks a lot @paulocoutinhox. We will give it a try

**Comment by paulocoutinhox** [comment]
I will close, feel free to reopen if need
